name: coca
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  flutter_svg: ^2.1.0
  google_fonts: ^6.2.1
  gap: ^3.0.1
  pinput: ^5.0.1
  modal_bottom_sheet: ^3.0.0
  equatable: ^2.0.7
  flutter_staggered_grid_view: ^0.7.0
  xml: ^6.5.0
  linkfy_text: ^1.1.6
  go_router: ^15.1.1
  transparent_image: ^2.0.1
  flutter_native_splash: ^2.4.6
  appflowy_board: ^0.1.2
  appflowy_editor: ^5.2.0
  percent_indicator: ^4.2.5
  intl: ^0.19.0
  animate_do: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  flutter_gen_runner: ^5.10.0
  flutter_launcher_icons: ^0.14.3
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_background: "#0062FF"

flutter_gen:
  integrations:

flutter:
  uses-material-design: true
  assets:
     - assets/images/icons/
     - assets/images/
     - assets/images/avatar/
     - assets/images/logo/
     - assets/images/editor/
  shaders:
     - assets/shaders/scroll_view_fade.frag